collectors:
- address: 35.194.97.218:2055
templates:
- id: 1033
  template:
  - SourceIPv4Address
  - DestinationIPv4Address
  - IpClassOfService
  - ProtocolIdentifier
  - SourceTransportPort
  - DestinationTransportPort
  - IcmpTypeCodeIPv4
  - IngressInterface
  - VlanId
  - SourceIPv4PrefixLength
  - DestinationIPv4PrefixLength
  - BgpSourceAsNumber
  - BgpDestinationAsNumber
  - IpNextHopIPv4Address
  - TcpControlBits
  - EgressInterface
  - MinimumTTL
  - MaximumTTL
  - FlowEndReason
  - IpVersion
  - BgpNextHopIPv4Address
  - FlowDirection
  - Dot1qVlanId
  - Dot1qCustomerVlanId
  - FragmentIdentification
  - OctetDeltaCount
  - PacketDeltaCount
  - FlowStartMilliseconds
  - FlowEndMilliseconds

flowsets:
- flowSetId: 1033
  flow:
  - FlowEndMilliseconds:      0x000001819e9d896b
    FlowStartMilliseconds:    0x0000000000002118
    OctetDeltaCount:          8482
    PacketDeltaCount:         80
    IpVersion:                4
    IngressInterface:         0
    EgressInterface:          0
    FlowDirection:            0
    SourceIPv4Address:        0x0a010001
    DestinationIPv4Address:   0x0a010002
    SourceTransportPort:      22
    DestinationTransportPort: 63153
    TcpControlBits:           0x18
    ProtocolIdentifier:       6
  - FlowEndMilliseconds:      0x000001819e9d896b
    FlowStartMilliseconds:    0x0000000000002118
    OctetDeltaCount:          8482
    PacketDeltaCount:         80
    IpVersion:                4
    IngressInterface:         0
    EgressInterface:          0
    FlowDirection:            0
    SourceIPv4Address:        0x0b010001
    DestinationIPv4Address:   0x0b010002
    SourceTransportPort:      22
    DestinationTransportPort: 63153
    TcpControlBits:           0x18
    ProtocolIdentifier:       6
