maxIpfixMessageLen: 100
timerFinishedDrainSeconds: 1
timerForceDrainSeconds: 30
timerTemplateFlushSeconds: 60
outputs:
- log:
    file: /tmp/flowlog.json
    hooks:
    - name: hostname addition
      command: ./misc/hook_command_example_dummy.sh
    - name: shell to resolve hostname
      shell: |
        #!/bin/sh
        echo `cat` | jq --arg hostname $(hostname) '. + {hostname: $hostname}'
    - name: shell to resolve ifname from ifindex
      shell: |
        #!/bin/sh
        IN=$(cat)
        I_IDX=$(echo $IN | jq .ingressIfindex -r)
        E_IDX=$(echo $IN | jq .egressIfindex -r )
        I_NAME=$(ip -n ns0 -j link | jq --argjson idx $I_IDX '.[] | select(.ifindex == $idx) | .ifname' -r)
        E_NAME=$(ip -n ns0 -j link | jq --argjson idx $E_IDX '.[] | select(.ifindex == $idx) | .ifname' -r)
        echo $IN | jq --arg i_name $I_NAME --arg e_name $E_NAME '. + {ingressIfname: $i_name, egressIfname: $e_name}'
