maxIpfixMessageLen: 100
timerFinishedDrainSeconds: 1
timerForceDrainSeconds: 30
timerTemplateFlushSeconds: 60
outputs:
- log:
    file: /tmp/flowlog.json
    hooks:
    - shell: |
        #!/bin/sh
        jq '[.[] | . + {
            foo1:"foo1",
            foo2:"foo2",
            foo3:"foo3",
            foo4:"foo4",
            foo5:"foo5",
            foo6:"foo6",
            foo7:"foo7",
            foo8:"foo8"
            }]'
